### ISSUE TITLE
openid放到哪里？

### ISSUE THREAD

**Issue by tonive** [Rabithua/memos_wmp#10]
得到了自己服务器上的openid放在哪里呢？

**Comment by Rabithua** [comment]
你是指hostId吗？这个是之前做注册用到的，现在新版的注册已经不需要hostId了，只需要后台开放注册就可以了

**Comment by tonive** [comment]
好的谢谢，就是按照教程，每次都定向到memos.wowo.club呢？不是应该到我的服务器端吗

**Comment by Rabithua** [comment]
miniprogram\pages\webview\webview.wxml 这个文件里面改下就ok了，同时微信小程序后台需要添加下业务域名才能线上使用，这个地方应该写成变量的，下个版本修复。

**Comment by tonive** [comment]
好的我在试试，谢谢
