### ISSUE TITLE
遇到的问题

### ISSUE THREAD

**Issue by eryajf** [Rabithua/memos_wmp#18]
- 部署流程第4步，我这边导入项目之后，appid就是固定了的，不让写自己申请的。
- 另外项目运行之后，登陆的时候总是401，但确定用户名密码都正确，而且看服务请求也确实请求到了自己的memos。

**Comment by Rabithua** [comment]
emm，等我测一下哈

**Comment by Rabithua** [comment]
你是用的我打包的最新版本吗

**Comment by eryajf** [comment]
是的，刚拉的代码

**Comment by Rabithua** [comment]
>> 部署流程第4步，我这边导入项目之后，appid就是固定了的，不让写自己申请的。
![image](https://user-images.githubusercontent.com/34543831/222448864-d8d47fa3-5e28-4c1d-a191-951b4389a34f.png)

**Comment by Rabithua** [comment]
> 另外项目运行之后，登陆的时候总是401，但确定用户名密码都正确，而且看服务请求也确实请求到了自己的memos。
这个能给一下你的网站吗，我这边测试是正常的，最好有一个测试的小账号

**Comment by eryajf** [comment]
我这里导入项目的时候，APPID是这样的，是个无法编辑的框，看起来是Mac和Windows有点不一样

<img width="804" alt="image" src="https://user-images.githubusercontent.com/33259379/222449460-18a2133f-54ed-465c-9996-529c1455e93c.png">

**Comment by Rabithua** [comment]
欸，确实不太一样，不过这个应该没有影响，正常打开编译成功了应该就没什么问题，401的话不太清楚是什么问题，你可以仔细看看接口的报错信息，我记得好像把错误的请求都打印了

**Comment by eryajf** [comment]
401的意思就是用户名密码错误，但是我用的肯定是正确的用户名密码呢

**Comment by eryajf** [comment]
报错信息如下：

```
{error: "code=401, message=User not found with email ", message: "User not found with email "}
```

另外就是我这边点击注册按钮，似乎没有反应

**Comment by Rabithua** [comment]
![image](https://user-images.githubusercontent.com/34543831/222450938-02dc5d7f-deee-4618-8da9-2803b3b21b77.png)
这里修改了吗

**Comment by eryajf** [comment]
改了，已经能看到请求的域名是我的域名了

**Comment by Rabithua** [comment]
哎，那这个就不太清楚了，我也没有遇到这种情况，你可以试试 `用户名/邮箱` 加密码的不同组合，或者新开个账号试试

**Comment by eryajf** [comment]
好吧，新建了账号，也还不行，那先这样吧

**Comment by in-dream** [comment]
message：Error: app.json: 未找到 ["pages"][3] 对应的 pages/webview/webview.js 文件
 请问这是什么情况？
