### ISSUE TITLE
归档恢复

### ISSUE THREAD

**Issue by Juskinbo** [Rabithua/memos_wmp#19]
是否考虑实现将归档恢复，目前只能删除，无法恢复。

**Comment by Rabithua** [comment]
可以恢复，已经归档的，打开底部折叠归档的卡片，点击删除按钮就会取消归档状态

**Comment by Rabithua** [comment]
![image](https://user-images.githubusercontent.com/34543831/222668703-e1c868b4-a219-4436-8df0-90af804efe95.png)
