### ISSUE TITLE
导入微信小程序开发者工具后报错，提示painter未找到

### ISSUE THREAD

**Issue by w905581962** [Rabithua/memos_wmp#3]
![image](https://user-images.githubusercontent.com/40052692/202102611-2ffd0dea-c502-46a0-bf98-2740069052df.png)

如图所示，导入微信小程序开发者工具后报错，提示painter未找到

使用的是git 命令clone下来的

另外麻烦问一下openId是什么时候需要配置的？

**Comment by Rabithua** [comment]
已更新，重新下载下master分支导入微信小程序开发者工具即可。

**Comment by w905581962** [comment]
![image](https://user-images.githubusercontent.com/40052692/202331335-ce9decc6-0cce-41e3-ae81-6b953ca33e55.png)
又有了其他的报错信息

**Comment by Rabithua** [comment]
这个应该是project.config.json文件的问题（https://developers.weixin.qq.com/miniprogram/dev/devtools/compilets.html）。
在setting下添加`"useCompilerPlugins": ["typescript"],`
修改后的源码导入直接打开是没问题的，可能是你没删掉之前的源码吧？

**Comment by w905581962** [comment]
我在删除所有缓存后就可以了，感谢
