### ISSUE TITLE
左侧切换中英文异常

### ISSUE THREAD

**Issue by wutianaaa** [Rabithua/memos_wmp#37]
左侧的弹出框中Language切换，报错something wrong!   
中英文切换不太灵敏，还会影响网页的切换

**Comment by Rabithua** [comment]
这个是bug，测试分支已经修复了，稍后会更新小程序

**Comment by wutianaaa** [comment]
ok，谢谢大佬的辛苦，有交流群吗

**Comment by Rabithua** [comment]
没有，memo的tg群，discord我都在
