### ISSUE TITLE
上传后提示：无依赖代码文件数14 (110KB)，体验版无法登陆使用！

### ISSUE THREAD

**Issue by lg-yyds** [Rabithua/memos_wmp#44]

**Comment by Rabithua** [comment]
详情-本地设置-上传时过滤无依赖文件
打开试试

**Comment by lg-yyds** [comment]
> 以下文件没有被打包上传：
components/painter/painter.js
components/painter/painter.json
components/painter/painter.wxml
miniprogram_npm/lottie-miniprogram/index.d.ts
components/painter/lib/calc.js
components/painter/lib/downloader.js
components/painter/lib/gradient.js
components/painter/lib/qrcode.js
components/painter/lib/pen.js
components/painter/lib/sha1.js
components/painter/lib/util.js
components/painter/lib/wx-canvas.js

还是不行，不能用，出不来版本号，软件里用着没问题

**Comment by Rabithua** [comment]
应该是域名没配置好的问题，看看业务域名加了没
