### ISSUE TITLE
开发者工具配置遇到问题

### ISSUE THREAD

**Issue by xiaosutai** [Rabithua/memos_wmp#61]
大佬，我修改了这边的配置，但是在左侧模拟区登录账号无法登录，这个怎么解决？

![image](https://github.com/Rabithua/memos_wmp/assets/88956346/c80ba2c0-f9e4-480c-8f7c-9bb86d77cb78)
![image](https://github.com/Rabithua/memos_wmp/assets/88956346/928b95a2-8b7e-4924-a42e-07360e21dcac)

**Comment by Rabithua** [comment]
看了下，网站无法正常打开，nginx没配置好吧，网址没问题的话，页面会出现版本号的，不然就是UNKNOWN，另外backendURL不需要设置，填了也没作用，这是一个单独的外挂后端

**Comment by xiaosutai** [comment]
再问下哈，这个我看了下，显示的是未知错误，nginx访问日志也在下面，话说nginx怎么配置，我pc或手机浏览器访问nginx地址都是正常的。
![image](https://github.com/Rabithua/memos_wmp/assets/88956346/60fab042-4088-47c1-985c-8408b9971ffc)
![image](https://github.com/Rabithua/memos_wmp/assets/88956346/c25ad6ad-0c95-4f29-97ac-7c670fc9e6e6)

**Comment by Rabithua** [comment]
你是最新版的吧？小程序现在只适配0.13.1
<img width="431" alt="image" src="https://github.com/Rabithua/memos_wmp/assets/34543831/285169f9-0f48-458b-a8d6-130bbe6fbfa9">

**Comment by xiaosutai** [comment]
嗯，这样的啊，我是最新的，我看看能不能回去到0.13.1版本
