### ISSUE TITLE
是否可以做一个详细的适合小白的教程

### ISSUE THREAD

**Issue by 307836997** [Rabithua/memos_wmp#63]
是否可以做一个详细的适合小白的教程
包括1.微信小程序如何修改,(对于看不懂代码的我来说新版本已经不会修改小程序文件)
2.如何关联到微信公众号(演示的麦默笔记的公众号真的非常的棒.)

我发现作者对项目开发的积极性越来越差.?是否可以做付费机制买断付费等方式支持作者?

**Comment by Rabithua** [comment]
有一说一，更新一直在持续，一般空闲时间都会改改清单的bug或者新需求，只是没有对usememos最新版的支持，因为web版也做了魔改，并且更新到最新版目前对我来说并没有太大必要，旧版已经够用了。

**Comment by Rabithua** [comment]
https://github.com/Rabithua/memos_wmp/releases/tag/v0.16.0
更了，根据最新的`demo.usememos.com`适配了全功能。

**Comment by 307836997** [comment]
还是希望能做一下**适合小白的**新版的图文教程,或者视频内容.另外有qq或者vx群吗可以联系到组织.问一问..真的是菜.

**Comment by Rabithua** [comment]
https://www.bilibili.com/video/BV1Hp4y1w7oi/?spm_id_from=333.999.0.0&vd_source=f7a212214e5215b0167a3ad0658083aa
可以看看这个
