### ISSUE TITLE
大佬，为什么我的memos是15.1，但是微信开发者就改了一个地址，但是登陆时一直在转，是不是哪边 有问题？平时访问网站是没问题的

### ISSUE THREAD

**Issue by xiaosutai** [Rabithua/memos_wmp#68]
![image](https://github.com/Rabithua/memos_wmp/assets/88956346/4e5d223e-a829-4ef0-90c7-44dc9c8e25fc)
![image](https://github.com/Rabithua/memos_wmp/assets/88956346/fee0d5ea-6200-4d1b-a0cb-df331632553c)

**Comment by Rabithua** [comment]
域名多了一个 `/`

**Comment by xiaosutai** [comment]
> 域名多了一个 `/`

可以了，多谢
