### ISSUE TITLE
这里只能是邮箱登录, 优化一下可以用户名登录

### ISSUE THREAD

**Issue by ysicing** [Rabithua/memos_wmp#7]
https://github.com/Rabithua/memos_wmp/blob/3ae17ad08e3425dc8c825ed41fbe5904a55480f1/miniprogram/pages/welcom/index.js#L143

**Comment by Rabithua** [comment]
会在下个版本进行优化

**Comment by tonive** [comment]
请问，为什么按照流程之后还是不能登录和注册，已经开放注册了

**Comment by Rabithua** [comment]
@tonive 贴一下报错信息吧

**Comment by Rabithua** [comment]
下个版本一定😂

**Comment by Rabithua** [comment]
已支持用户名注册和登录😁
