### ISSUE TITLE
我是用群晖docker创建的memos

### ISSUE THREAD

**Issue by tonive** [Rabithua/memos_wmp#8]
群晖docker创建的memos，利用反向代理https，按照要求填写域名地址了，是否需要添加端口？，因为按照前面的步骤并不能进行登录注册

**Comment by Rabithua** [comment]
![image](https://user-images.githubusercontent.com/34543831/209469855-70bc6541-23cd-4c81-ba39-6d5ef9fff0cf.png)

打开一下试试，`小程序上线可用的话，需要保证域名已备案，开启https且公网可以正常访问`

**Comment by tonive** [comment]
群晖的公网是可以访问的，域名也备案了，但是打开后仍然定向访问到了menos.wowow.club这个网站，不知道为什么，我也在app.js里面修改了this.globaldata下的url地址

**Comment by Rabithua** [comment]
这就比较离谱了，贴下报错信息吧

**Comment by tonive** [comment]
<img width="938" alt="Snipaste_2023-01-03_23-11-20" src="https://user-images.githubusercontent.com/33473085/210385204-0c6e92d2-31c3-4f58-a6a8-a518b0e41280.png">

**Comment by Rabithua** [comment]
你打开的这个是webview，我在小程序内置了这个，并不算是小程序的功能，你回到welcom用测试账号登陆试试

**Comment by sexyfeifan** [comment]
你好？我想问一下你是群晖搭建的，那你的域名备案是怎么申请的？
